export enum ElementsActionTypes {
  ADD_ELEMENT_ACTION = '[Angular Element] Add survey question element',
  REMOVE_ELEMENT_ACTION = '[Angular Element] Remove survey question element',
  REMOVE_ELEMENT_MAP_ACTION = '[Angular Element] Remove element map',
  MOVE_ELEMENT_UP_ACTION = '[Angular Element] Move survey question element up',
  MOVE_ELEMENT_DOWN_ACTION = '[Angular Element] Move survey question element down',
  DRAG_ELEMENT_ACTION = '[Angular Element] Drag survey question element',
  QUESTION_ADD_TEXT_ACTION = '[Angular Question] Add question text',
  QUESTION_ADD_TYPE_ACTION = '[Angular Question] Add question type',
  QUESTION_UPDATE_MIN_ACTION = '[Angular Question] Update question max value',
  QUESTION_UPDATE_MAX_ACTION = '[Angular Question] Update question min value',
  QUESTION_REMOVE_VALUES_ACTION = '[Angular Question] Remove question values',
  QUESTION_UPDATE_PAGE_FLOW_MODIFIER_ACTION = '[Angular Question] UPDATE question page flow modifier',
  TOGGLE_IS_ACTIVE_ELEMENT_ACTION = '[Angular Element] Toggle isActive element',
  QUESTION_UPDATE_ANSWER_ACTION = '[Angular Question] Update question answer value',
  PARAGRAPH_UPDATE_HTML_ACTION = '[Angular Paragraph] Update paragraph HTML value',
  RESET_ELEMENTS_STATE = '[Angular Element] Reset elements state',
  IMPORT_ELEMENTS_STATE = '[Angular Element] Import elements state',
  IMPORT_ELEMENT = '[Angular Element] Import element',
  CLONE_ELEMENT_ACTION = '[Angular Element] Clone element',
}
